#!/bin/bash
OE_BRAND="MERP"
OE_CORE="core_master/odoo/"
OE_USER_MENU="core_master/odoo/addons/web/static/src/webclient/user_menu/user_menu_items.js"
OE_IMG="core_master/odoo/addons/web/static/img"

sed -i '/id: "documentation",/a hide: "true",' $OE_USER_MENU
sed -i '/id: "support",/a hide: "true",' $OE_USER_MENU
sed -i '/id: "settings",/a hide: "true",' $OE_USER_MENU
sed -i '/id: "account",/a hide: "true",' $OE_USER_MENU


files=$(grep -rl --exclude="Read*" --exclude-dir=$OE_IMG "Odoo" $OE_CORE | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/\bOdoo\b/$OE_BRAND/g'
files=$(grep -rl --exclude="Read*" --exclude-dir=$OE_IMG 'www.odoo.com' $OE_CORE | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/www.odoo.com/www.manzada.net/g'
files=$(grep -rl --exclude="Read*" --exclude-dir=$OE_IMG 'odoo.com' $OE_CORE | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/accounts.odoo.com/accounts.manzada.net/g'
files=$(grep -rl --exclude="Read*" --exclude-dir=$OE_IMG 'odoo@example.com' $OE_CORE | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/odoo@example.com/mail@example.com/g'
files=$(grep -rl --exclude="Read*" --exclude-dir=$OE_IMG 'Negara-Negara' $OE_CORE | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/Negara-Negara/Negara/g'
files=$(grep -rl --exclude="Read*" --exclude-dir=$OE_IMG 'hari-hari' $OE_CORE | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/hari-hari/hari/g'
files=$(grep -rl --exclude="Read*" --exclude-dir=$OE_IMG 'Vendor Terbai' $OE_CORE | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/Vendor Terbai/Vendor Terbaik/g'
files=$(grep -rl --exclude="Read*" --exclude-dir=$OE_IMG 'Vendor Terbaikk' $OE_CORE | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/Vendor Terbaikk/Vendor Terbaik/g'
files=$(grep -rl --exclude="Read*" --exclude-dir=$OE_IMG 'Kategori Produk Terbai' $OE_CORE | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/Kategori Produk Terbai/Kategori Produk Terbaik/g'
files=$(grep -rl --exclude="Read*" --exclude-dir=$OE_IMG 'Kategori-Kategori Terbaik' $OE_CORE | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/Kategori-Kategori Terbaik/Kategori Produk Terbaik/g'
files=$(grep -rl --exclude="Read*" --exclude-dir=$OE_IMG 'Salespeople Terbaik' $OE_CORE | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/Salespeople Terbaik/Salesman Terbaik/g'
files=$(grep -rl --exclude="Read*" --exclude-dir=$OE_IMG 'Memerintahkan' $OE_CORE | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/Memerintahkan/Ordered/g'
